#!/usr/bin/python3.6
import urllib3 
import json
http = urllib3.PoolManager() 
def lambda_handler(event, context): 
    url = "https://outlook.office.com/webhook/YOUR_WEBHOOK_URL"
    if (event['source'] == 'aws.signin'): #replace aws.signin with your desired service
        eventtotext=json.dumps(event)
        msg = {
            "text": eventtotext
        } 
    encoded_msg = json.dumps(msg).encode('utf-8')
    resp = http.request('POST',url, body=encoded_msg)
   
