#!/usr/bin/python3.6
import urllib3 
import json
http = urllib3.PoolManager() 
def lambda_handler(event, context): 
    url = "http://WEB-hook" #Your webhook https is here
    if (event['Records'][0]['eventSource'] == 'aws:sqs'):
        msg = {"Text": event['Records'][0]['body']}
    else:    
        msg = {
            "text": event['Records'][0]['Sns']['Message']
        }
    encoded_msg = json.dumps(msg).encode('utf-8')
    resp = http.request('POST',url, body=encoded_msg)
   
